name: NPM Install, Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.CR_PAT }}
        BUILD_SCRIPT: npm install && BASE_PATH='/wikidata-wikibase-architecture/' npm run build
        BUILD_DIR: .vuepress/dist/
